import React,{useEffect,useMemo,useState} from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, Share2, Download, Copy, BadgeCheck, Database, MapPin, TestTube2, Dna, Microscope, CircleDot, Activity, Thermometer, TableProperties, FileText, Images, FlaskConical, BookOpen, Archive, Wrench, Building2, Mail, CalendarDays, Edit3, Printer, Check, ExternalLink, ShieldCheck } from 'lucide-react';
import { getPhage } from '../api.js';
import ShareModal from '../components/ShareModal.jsx';
import SectionCard,{KV} from '../components/SectionCard.jsx';
import PhageArt from '../components/PhageArt.jsx';
import GrowthCurve from '../components/GrowthCurve.jsx';

const API_BASE=import.meta.env.VITE_API_BASE||(import.meta.env.DEV?'http://localhost:8787/api':'/api');
export default function PhageDetail(){
  const {id}=useParams(); const [p,setP]=useState(null); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [share,setShare]=useState(false); const [copied,setCopied]=useState(false);
  useEffect(()=>{let active=true;setLoading(true);setP(null);setError('');getPhage(id).then(r=>{if(active)setP(r.item)}).catch(e=>{if(active)setError(e.message||'Unable to load this record.')}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[id]);
  const quality=useMemo(()=>p?recordQuality(p):0,[p]);
  if(loading)return <div className="page-width detail-loading"><div className="skeleton detail-hero-skeleton"/>{[1,2,3,4,5,6].map(x=><div className="skeleton detail-section-skeleton" key={x}/>)}</div>;
  if(!p)return <div className="page-width empty-state"><h2>{error||'Record not found'}</h2><p>The record could not be opened. Return to the repository and try again.</p><Link className="outline-button" to="/database">BACK TO DATABASE</Link></div>;
  const cite=`PhageDB. ${p.name} (${p.repositoryId}). ${p.institute||'Repository record'}. Version ${p.version||'1.0'}. ${window.location.href}`;
  const copyCitation=async()=>{await navigator.clipboard.writeText(cite);setCopied(true);setTimeout(()=>setCopied(false),1400)};
  return <div className="page-width detail-page">
    <div className="profile-toolbar"><Link to="/database" className="back-link"><ArrowLeft/> Back to repository</Link><div className="detail-actions"><button className="outline-button" onClick={()=>setShare(true)}><Share2/> Share</button><button className="outline-button" onClick={copyCitation}>{copied?<Check/>:<Copy/>} Cite</button><button className="icon-button big" onClick={()=>window.print()} title="Print / Save PDF"><Printer/></button>{localStorage.getItem('phagedb_token')&&<Link className="icon-button big" to={`/edit/${p.id}`} title="Edit record"><Edit3/></Link>}</div></div>
    <div className="print-masthead"><img src="/gtu-logo.png" alt="Gujarat Technological University"/><div><strong>GUJARAT TECHNOLOGICAL UNIVERSITY</strong><span>BACTERIOPHAGE REPOSITORY · SCIENTIFIC RECORD</span></div></div>
    <header className="profile-heading"><span>SCIENTIFIC REPOSITORY RECORD</span><h1>PHAGE PROFILE — {p.name}</h1><p>{p.repositoryId} · {p.accession} · {p.host}</p><div className="identity-badges"><span className="status-badge"><BadgeCheck/> {p.status}</span><span>{p.phageType}</span><span>{p.genomeType}</span><span>{p.visibility||'Public'}</span><span>Version {p.version||'1.0'}</span></div><div className="quality-row"><div><span>Metadata completeness</span><strong>{quality}%</strong></div><div className="quality-track"><i style={{width:`${quality}%`}}/></div></div></header>

    <div className="profile-grid">
      <SectionCard number="1" title="PHAGE IDENTITY" icon={Database} className="identity-section"><div className="profile-phage-art"><PhageArt/></div><div className="identity-kvs"><KV label="Repository ID" value={p.repositoryId}/><KV label="Phage name" value={p.name}/><KV label="Alternative name" value={p.alternativeName}/><KV label="Repository accession" value={p.accession}/><KV label="Current status" value={p.status}/></div></SectionCard>
      <SectionCard number="2" title="ISOLATION INFORMATION" icon={MapPin}><KV label="Isolation date" value={fmtDate(p.isolationDate)}/><KV label="Isolation location" value={p.isolationSite}/><KV label="GPS coordinates" value={p.latitude&&p.longitude?`${p.latitude}, ${p.longitude}`:'—'}/><KV label="Sample type" value={p.sampleType}/><KV label="Environmental source" value={p.environmentalSource}/><KV label="Collected by" value={p.collectedBy}/><KV label="Isolation method" value={p.isolationMethod}/><KV label="Host used for isolation" value={p.hostUsedForIsolation}/></SectionCard>
      <SectionCard number="3" title="HOST INFORMATION" icon={TestTube2}><KV label="Primary host" value={p.host}/><KV label="Host strain" value={p.hostStrain}/><KV label="ATCC number" value={p.atcc}/><KV label="Host origin" value={p.hostOrigin}/><KV label="Gram stain" value={p.gramStain}/><KV label="Clinical importance" value={p.clinicalImportance}/><KV label="Antibiotic resistance profile" value={p.antibioticResistance}/></SectionCard>
      <SectionCard number="4" title="TAXONOMIC CLASSIFICATION" icon={Dna}><KV label="Order" value={p.order}/><KV label="Family" value={p.family}/><KV label="Subfamily" value={p.subfamily}/><KV label="Genus" value={p.genus}/><KV label="Species" value={p.species}/><KV label="ICTV status" value={p.ictvStatus}/><KV label="Genome type" value={p.genomeType}/></SectionCard>
      <SectionCard number="5" title="MORPHOLOGICAL CHARACTERISTICS" icon={Microscope} className="media-section"><div className="science-visual tem-visual"><PhageArt/></div><KV label="Capsid shape" value={p.capsidShape}/><KV label="Tail type" value={p.tailType}/><KV label="Capsid diameter" value={p.capsidDiameter}/><KV label="Tail length" value={p.tailLength}/><KV label="Tail width" value={p.tailWidth}/><KV label="Collar" value={p.collar}/><KV label="Base plate" value={p.basePlate}/><KV label="Tail fibers" value={p.tailFibers}/><KV label="Morphotype" value={p.morphotype}/></SectionCard>
      <SectionCard number="6" title="PLAQUE CHARACTERISTICS" icon={CircleDot} className="media-section"><div className="science-visual plaque-visual">{[1,2,3,4,5,6,7,8,9,10,11,12].map(x=><i key={x}/>)}</div><KV label="Plaque diameter" value={p.plaqueDiameter}/><KV label="Plaque appearance" value={p.plaqueAppearance}/><KV label="Halo" value={p.halo}/><KV label="Margin" value={p.margin}/><KV label="Elevation" value={p.elevation}/><p className="section-note">{p.plaqueMorphology||'No plaque morphology description recorded.'}</p></SectionCard>
      <SectionCard number="7" title="BIOLOGICAL CHARACTERISTICS" icon={Activity}><KV label="Adsorption time" value={p.adsorptionTime}/><KV label="Adsorption rate constant" value={p.adsorptionRate}/><KV label="Latent period" value={p.latentPeriod}/><KV label="Eclipse period" value={p.eclipsePeriod}/><KV label="Rise period" value={p.risePeriod}/><KV label="Burst size" value={p.burstSize}/><KV label="Optimal MOI" value={p.optimalMoi}/><KV label="Life cycle" value={p.lifeCycle||p.phageType}/></SectionCard>
      <SectionCard number="8" title="GROWTH PARAMETERS" icon={Activity} className="wide-section"><div className="kv-four"><KV label="Optimal growth temperature" value={p.growth?.temperature}/><KV label="Optimal pH" value={p.growth?.ph}/><KV label="Optimal host density" value={p.growth?.hostDensity}/><KV label="Maximum PFU" value={p.growth?.maximumPfu}/></div><h4 className="chart-title">ONE-STEP GROWTH CURVE</h4><GrowthCurve values={p.growth?.curve}/></SectionCard>
      <SectionCard number="9" title="HOST RANGE" icon={TableProperties} className="wide-section"><HostRange rows={p.hostRange}/></SectionCard>
      <SectionCard number="10" title="TEMPERATURE STABILITY" icon={Thermometer}><Stability rows={p.temperatureStability} head="Temperature (°C)"/></SectionCard>
      <SectionCard number="11" title="pH STABILITY" icon={Activity}><Stability rows={p.phStability} head="pH"/></SectionCard>
      <SectionCard number="12" title="GENOME INFORMATION" icon={Dna}><KV label="Sequencing platform" value={p.sequencingPlatform}/><KV label="Genome size" value={p.genomeSize}/><KV label="GC content" value={p.gcContent}/><KV label="Genome type" value={p.genomeType}/><KV label="Genome ends" value={p.genomeEnds}/><KV label="Assembly" value={p.assembly}/><KV label="Coverage" value={p.coverage}/><KV label="GenBank accession" value={p.genbank}/></SectionCard>
      <SectionCard number="13" title="GENOME ANNOTATION" icon={Dna}><KV label="Total ORFs" value={p.annotation?.totalOrfs}/><KV label="Coding density" value={p.annotation?.codingDensity}/><KV label="tRNA genes" value={p.annotation?.trna}/><KV label="rRNA" value={p.annotation?.rrna}/><KV label="Integrase" value={p.annotation?.integrase}/><KV label="Repressor protein" value={p.annotation?.repressor}/><KV label="Virulence genes" value={p.annotation?.virulence}/><KV label="AMR genes" value={p.annotation?.amr}/><KV label="Lysogeny genes" value={p.annotation?.lysogeny}/><KV label="Lifestyle prediction" value={p.annotation?.lifestyle}/></SectionCard>
      <SectionCard number="14" title="FUNCTIONAL PROTEINS" icon={Dna}><SimpleTable headers={['Protein','Predicted function']} rows={p.proteins||[]}/></SectionCard>
      <SectionCard number="15" title="LABORATORY INFORMATION" icon={Archive}><KV label="Current stock titer" value={p.lab?.stockTiter}/><KV label="Storage buffer" value={p.lab?.buffer}/><KV label="Storage temperature" value={p.lab?.storageTemperature}/><KV label="Cryoprotectant" value={p.lab?.cryoprotectant}/><KV label="Freeze-thaw cycles" value={p.lab?.freezeThaw}/><KV label="Freezer location" value={p.lab?.freezer}/><KV label="Rack" value={p.lab?.rack}/><KV label="Box" value={p.lab?.box}/><KV label="Position" value={p.lab?.position}/></SectionCard>
      <SectionCard number="16" title="EXPERIMENTAL PROTOCOLS (SOPs)" icon={FileText} className="wide-section"><DocTiles items={p.protocols||[]} label="PDF"/></SectionCard>
      <SectionCard number="17" title="IMAGES" icon={Images} className="wide-section"><Gallery items={p.images||[]}/></SectionCard>
      <SectionCard number="18" title="DOWNLOADS" icon={Download} className="wide-section"><div className="download-grid"><DownloadTile label="Metadata JSON" href={`${API_BASE}/phages/${p.id}/download/json`}/><DownloadTile label="Metadata CSV" href={`${API_BASE}/phages/${p.id}/download/csv`}/><DownloadTile label="Genome FASTA" href={`${API_BASE}/phages/${p.id}/download/fasta`}/>{(p.downloads||[]).filter(x=>!String(x).toLowerCase().includes('fasta')).map(x=><DownloadTile key={x} label={x} disabled/>)}</div></SectionCard>
      <SectionCard number="19" title="APPLICATIONS" icon={FlaskConical}><div className="tag-cloud">{(p.applications||[]).map(x=><span key={x}>{x}</span>)}{!(p.applications||[]).length&&<span className="muted">No applications recorded.</span>}</div></SectionCard>
      <SectionCard number="20" title="PUBLICATIONS" icon={BookOpen}><div className="publication-list">{(p.publications||[]).map((x,i)=><div key={i}><FileText/><span>{x}</span></div>)}{!(p.publications||[]).length&&<span className="muted">No publications linked.</span>}</div></SectionCard>
      <SectionCard number="21" title="REPOSITORY METADATA" icon={ShieldCheck}><KV label="Date added" value={fmtDate(p.dateAdded||p.createdAt)}/><KV label="Last updated" value={fmtDate(p.lastUpdated||p.updatedAt)}/><KV label="Verified by" value={p.verifiedBy}/><KV label="Curator" value={p.curator}/><KV label="Data version" value={p.version}/><KV label="Quality status" value={p.qualityStatus}/><KV label="Availability" value={p.visibility}/></SectionCard>
      <SectionCard title="ADDITIONAL RESEARCH TOOLS" icon={Wrench} className="wide-section optional-tools-section"><div className="tool-grid">{(p.relatedTools||[]).map(x=><button key={x} className="tool-tile" title="Integration-ready feature"><Wrench/><span>{x}</span><small>Integration-ready</small></button>)}{!(p.relatedTools||[]).length&&<p className="muted">Add similarity, phylogeny and comparative genomics integrations as sequence data becomes available.</p>}</div></SectionCard>
    </div>
    <div className="record-citation"><strong>Suggested citation</strong><span>{cite}</span><button onClick={copyCitation}>{copied?<Check/>:<Copy/>}</button></div>
    {share&&<ShareModal phage={p} onClose={()=>setShare(false)}/>} 
  </div>
}
function Summary({icon:Icon,label,value}){return <div className="summary-card"><Icon/><div><span>{label}</span><strong>{value||'—'}</strong></div></div>}
function fmtDate(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}
function recordQuality(p){const fields=['repositoryId','name','phageType','host','hostStrain','genomeType','isolationSite','isolationDate','institute','contact','plaqueMorphology','sequencingPlatform','genomeSize','gcContent','family','lifeCycle','verifiedBy'];return Math.round(fields.filter(k=>p[k]&&p[k]!=='—'&&p[k]!=='Unknown').length/fields.length*100)}
function HostRange({rows=[]}){if(!rows.length)return <p className="muted">No host-range experiment recorded.</p>;const susceptible=rows.filter(r=>r.result).length;return <><table className="data-table"><thead><tr><th>Bacterial host</th><th>Strain</th><th>Result</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r.host}</td><td>{r.strain}</td><td className={r.result?'positive':'negative'}>{r.result?'✓ Susceptible':'✕ Resistant / no lysis'}</td></tr>)}</tbody></table><div className="metric-row"><span><strong>{rows.length}</strong> hosts tested</span><span><strong>{susceptible}</strong> susceptible</span><span><strong>{Math.round(susceptible/rows.length*100)}%</strong> host range</span></div></>}
function Stability({rows=[],head}){if(!rows.length)return <p className="muted">No stability data recorded.</p>;return <table className="data-table compact"><thead><tr><th>{head}</th><th>Stability</th></tr></thead><tbody>{rows.map((r,i)=><tr key={i}><td>{r[0]}</td><td className={['Stable','Excellent','Good','Yes'].includes(r[1])?'positive':['No','Inactive'].includes(r[1])?'negative':'warning'}>{r[1]}</td></tr>)}</tbody></table>}
function SimpleTable({headers,rows=[]}){if(!rows.length)return <p className="muted">No functional annotation added.</p>;return <table className="data-table compact"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table>}
function DocTiles({items=[],label}){return <div className="doc-grid">{items.length?items.map(x=><button className="doc-tile" key={x}><FileText/><strong>{x}</strong><small>{label}</small></button>):<p className="muted">No protocols uploaded.</p>}</div>}
function Gallery({items=[]}){return <div className="gallery-grid">{items.length?items.map((x,i)=><div className={`gallery-tile ${x.kind||''}`} key={i}><div className="gallery-visual"><span>{x.kind==='tem'?'TEM':x.kind==='plaque'?'PLAQUE':x.kind==='lawn'?'HOST LAWN':'SAMPLE'}</span></div><strong>{x.label}</strong></div>):<p className="muted">No research images uploaded.</p>}</div>}
function DownloadTile({label,href,disabled}){return disabled?<button className="download-tile disabled" title="Attach a real file to activate"><Download/><span>{label}</span><small>Awaiting file</small></button>:<a className="download-tile" href={href}><Download/><span>{label}</span><small>Download</small></a>}
